before_install:
  - rvm get stable
  - rvm install ruby 2.2.3
  - wget https://keplerproject.github.io/luarocks/releases/luarocks-2.2.2.tar.gz -O luarocks-2.2.2.tar.gz
  - tar -xvf luarocks-2.2.2.tar.gz
  - cd luarocks-2.2.2
  - ./configure
  - make build
  - sudo make install
  - cd ../

install:
  - luarocks install luacheck
  - gem install awesome_bot

script:
  # Run luacheck
  - luacheck .
  # Check for link problems
  - awesome_bot README.md --allow-dupe

addons:
  apt:
    packages:
      - lua5.2

notifications:
  email: false
